# Generated by Django 3.2.18 on 2023-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('email_id', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('education', models.CharField(max_length=200, verbose_name='Education')),
                ('mark', models.CharField(max_length=200, verbose_name='Score')),
                ('cutoff_mark', models.CharField(max_length=200, verbose_name='Cutoff Mark')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Student Image')),
            ],
        ),
    ]
