# Generated by Django 3.2.18 on 2023-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='Score',
            field=models.CharField(max_length=200, null=True, verbose_name='Score'),
        ),
    ]
