# Generated by Django 3.2.18 on 2023-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_detail_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_College_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='College Name')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('dob', models.DateField()),
                ('OC', models.CharField(max_length=20, verbose_name='OC')),
                ('BC', models.CharField(max_length=200, verbose_name='BC')),
                ('BCM', models.CharField(max_length=200, verbose_name='BCM')),
                ('MBCV', models.CharField(max_length=200, verbose_name='MBCV')),
                ('MBCDNC', models.TextField(blank=True, null=True, verbose_name='MBCDNC')),
                ('MBA', models.CharField(max_length=200, null=True, verbose_name='MBA')),
                ('SC', models.CharField(default='India', max_length=100, verbose_name='SC')),
                ('SCA', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='SCA')),
                ('ST', models.CharField(blank=True, max_length=100, null=True, verbose_name='ST')),
            ],
        ),
    ]
