# Generated by Django 3.2.18 on 2023-04-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_engineering_college_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineering_college_detail',
            name='dob',
        ),
    ]
