# Generated by Django 3.2.18 on 2023-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_engineering_college_detail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='college_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='degree',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Department'),
        ),
    ]
