# Generated by Django 3.2.18 on 2023-04-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230401_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineering_College_Detail',
        ),
    ]
