# Generated by Django 3.2.18 on 2023-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_engineering_college_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='BC',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='BC'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='BCM',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='BCM'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='MBCV',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MBCV'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='OC',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OC'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='SC',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SC'),
        ),
        migrations.AlterField(
            model_name='engineering_college_detail',
            name='SCA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SCA'),
        ),
    ]
