# Generated by Django 3.2.18 on 2023-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230401_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agri_College_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name')),
                ('degree', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Degree')),
                ('department', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Department')),
                ('OC', models.CharField(blank=True, max_length=20, null=True, verbose_name='OC')),
                ('BC', models.CharField(blank=True, max_length=200, null=True, verbose_name='BC')),
                ('BCM', models.CharField(blank=True, max_length=200, null=True, verbose_name='BCM')),
                ('MBCV', models.CharField(blank=True, max_length=200, null=True, verbose_name='MBCV')),
                ('MBCDNC', models.TextField(blank=True, null=True, verbose_name='MBCDNC')),
                ('MBA', models.CharField(max_length=200, null=True, verbose_name='MBA')),
                ('SC', models.CharField(blank=True, max_length=100, null=True, verbose_name='SC')),
                ('SCA', models.CharField(blank=True, max_length=100, null=True, verbose_name='SCA')),
                ('ST', models.CharField(blank=True, max_length=100, null=True, verbose_name='ST')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_College_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name')),
                ('degree', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Degree')),
                ('department', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Department')),
                ('OC', models.CharField(blank=True, max_length=20, null=True, verbose_name='OC')),
                ('BC', models.CharField(blank=True, max_length=200, null=True, verbose_name='BC')),
                ('BCM', models.CharField(blank=True, max_length=200, null=True, verbose_name='BCM')),
                ('MBCV', models.CharField(blank=True, max_length=200, null=True, verbose_name='MBCV')),
                ('MBCDNC', models.TextField(blank=True, null=True, verbose_name='MBCDNC')),
                ('MBA', models.CharField(max_length=200, null=True, verbose_name='MBA')),
                ('SC', models.CharField(blank=True, max_length=100, null=True, verbose_name='SC')),
                ('SCA', models.CharField(blank=True, max_length=100, null=True, verbose_name='SCA')),
                ('ST', models.CharField(blank=True, max_length=100, null=True, verbose_name='ST')),
            ],
        ),
    ]
