# Generated by Django 3.2.18 on 2023-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_agri_college_detail_medical_college_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='caste',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caste'),
        ),
    ]
