# Generated by Django 5.0.2 on 2024-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_student_detail_caste"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agri_College_Detail",
        ),
        migrations.DeleteModel(
            name="Medical_College_Detail",
        ),
        migrations.AddField(
            model_name="engineering_college_detail",
            name="skill",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Skill"
            ),
        ),
    ]
